# Map and Filter Functions

In [1]:
"""
map() returns every item in an iterable and filter() returns values if True.

"""

'\nmap() returns every item in an iterable and filter() returns values if True.\n\n'

# map()

In [5]:
menu = ["expresso", "mocha", "latte", "cappuccino", "cortado", "americano"]

def find_coffee (coffee):
    if coffee[0] == "c":
        return coffee
    
    
map_coffee = map(find_coffee, menu)
print(map_coffee)

for x in map_coffee:
    print(x)

<map object at 0x000001A5121806A0>
None
None
None
cappuccino
cortado
None

# filter()

In [6]:
filter_coffee = filter(find_coffee, menu)
print(filter_coffee)

for x in filter_coffee:
    print(x)
    
# see the difference in output in contast to the map()

<filter object at 0x000001A512183100>
cappuccino
cortado

In [9]:
# Comprehensions

"""
Comprehensions in Python are a way to create a new sequence from an already existing sequence.
There are four main types of comprehensions in Python: 

List comprehension 

Dictionary comprehension 

Set comprehension 

Generator comprehension
"""

'\nComprehensions in Python are a way to create a new sequence from an already existing sequence.\nThere are four main types of comprehensions in Python: \n\nList comprehension \n\nDictionary comprehension \n\nSet comprehension \n\nGenerator comprehension\n'

# List comprehension

In [10]:
data = [2,3,5,7,11,13,17,19,23,29,31]

# Ex1: List comprehension: updating the same list
data = [x+3 for x in data]
print("Updating the list: ", data)

# Ex2: List comprehension: creating a different list with updated values
new_data = [x*2 for x in data]
print("Creating new list: ", new_data)

# Ex3: With an if-condition: Multiples of four:
fourx = [x for x in new_data if x%4 == 0 ]
print("Divisible by four", fourx)

# Ex4: Alternatively, we can update the list with the if condition as well
fourxsub = [x-1 for x in new_data if x%4 == 0 ]
print("Divisible by four minus one: ", fourxsub)

# Ex5: Using range function:
nines = [x for x in range(100) if x%9 == 0]
print("Nines: ", nines)

Updating the list:  [5, 6, 8, 10, 14, 16, 20, 22, 26, 32, 34]
Creating new list:  [10, 12, 16, 20, 28, 32, 40, 44, 52, 64, 68]
Divisible by four [12, 16, 20, 28, 32, 40, 44, 52, 64, 68]
Divisible by four minus one:  [11, 15, 19, 27, 31, 39, 43, 51, 63, 67]
Nines:  [0, 9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99]

In [14]:
# List comprehension:
data = [x+3 for x in data]
print("Data generated by List comprehension: ", data)

# Regular for loop:
for x in range(len(data)):
    data[x] = data[x] + 3
    
print("Data generated by for loop : ", data)

Data generated by List comprehension:  [26, 27, 29, 31, 35, 37, 41, 43, 47, 53, 55]
Data generated by for loop :  [29, 30, 32, 34, 38, 40, 44, 46, 50, 56, 58]

# Dictionary Comprehension

# dict = { key:value for key, value in <sequence> if <condition> }

In [15]:
# Using range() function and no input list
usingrange = {x:x*2 for x in range(12)}
print("Using range(): ",usingrange)

# Lists
months = ["Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec"]
number = [1,2,3,4,5,6,7,8,9,10,11,12]

# Using one input list
numdict = {x:x**2 for x in number}
print("Using one input list to create dict: ", numdict)

# Using two input lists
months_dict = {key:value for (key, value) in zip(number, months)}
print("Using two lists: ", months_dict)

Using range():  {0: 0, 1: 2, 2: 4, 3: 6, 4: 8, 5: 10, 6: 12, 7: 14, 8: 16, 9: 18, 10: 20, 11: 22}
Using one input list to create dict:  {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144}
Using two lists:  {1: 'Jan', 2: 'Feb', 3: 'Mar', 4: 'Apr', 5: 'May', 6: 'June', 7: 'July', 8: 'Aug', 9: 'Sept', 10: 'Oct', 11: 'Nov', 12: 'Dec'}

In [16]:
"""
new_dict ={key:value for (key, value) in zip(list1, list2)}

Here we used the zip function that combines the two lists. When
the two lists are of unequal length, the length of the shorter
list is the length of the dictionary.
"""

'\nnew_dict ={key:value for (key, value) in zip(list1, list2)}\n\nHere we used the zip function that combines the two lists. When\nthe two lists are of unequal length, the length of the shorter\nlist is the length of the dictionary.\n'

# Set comprehension

In [17]:
set_a = {x for x in range(10,20) if x not in [12,14,16]}
print(set_a)

{10, 11, 13, 15, 17, 18, 19}

In [18]:
a = [[96], [69]]

print(''.join(list(map(str, a))))

[96][69]

In [19]:
z = ["alpha","bravo","charlie"]
new_z = [i[0]*2for i in z]
print(new_z)

['aa', 'bb', 'cc']

In [20]:
def sum(n):
   if n == 1:
       return 0
   return n + sum(n-1)

a = sum(5)
print(a)

14

In [25]:
some = ["aaa", "bbb"]

#1
def aa(some):
   return

In [26]:
#2
def aa(some, 5):
   return

SyntaxError: invalid syntax (2443969926.py, line 2)

In [27]:
#4
def aa():
   return "aaa"

In [29]:
#3
def aa():
   return

In [31]:
numbers = [15, 30, 47, 82, 95]
def lesser(numbers):
   return numbers < 50

small = list(filter(lesser, numbers))
print("Filetr applied : ", small)

small_1 = list(map(lesser,numbers))
print("Map applied : ", small_1)

Filetr applied :  [15, 30, 47]
Map applied :  [True, True, True, False, False]